apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: influscope-demo
  region: us-east-1

nodeGroups:
  - name: workers
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        ebs: true
        autoScaler: true

addons:
  - name: aws-ebs-csi-driver
