# --- API (The Gateway) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: influscope
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: hammo/influscope-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: influscope-config
          readinessProbe:
            httpGet:
              path: /search?q=ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    component: api
  ports:
    - port: 80
      targetPort: 8080

# --- Scraper (The Producer) ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  labels:
    app: influscope
    component: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scraper
  template:
    metadata:
      labels:
        component: scraper
    spec:
      containers:
        - name: scraper
          image: hammo/influscope-scraper:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: influscope-config
          # Note: Scraper depends on S3 service being active
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30

# --- Indexer (The Consumer) ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  labels:
    app: influscope
    component: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: indexer
  template:
    metadata:
      labels:
        component: indexer
    spec:
      containers:
        - name: indexer
          image: hammo/influscope-indexer:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: influscope-config
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8082
            initialDelaySeconds: 10