global:
  scrape_interval: 3s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'scraper'
    static_configs:
      - targets: ['scraper:8081']

  - job_name: 'indexer'
    static_configs:
      - targets: ['indexer:8082']

