# --- Scraper (The Producer) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  labels:
    app: influscope
    component: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scraper
  template:
    metadata:
      labels:
        component: scraper
    spec:
      containers:
        - name: scraper
          image: ghcr.io/anis-hammoudi/influscope/scraper:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: influscope-config
          # Scraper needs time to connect to S3/RabbitMQ
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
