name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Test & Build Scraper
        run: |
          cd scraper
          go mod download
          echo " Running Scraper Tests..."
          go test -v ./...
          echo " Building Scraper..."
          go build -v ./...

      - name: Test & Build Indexer
        run: |
          cd indexer
          go mod download
          echo " Running Indexer Tests..."
          go test -v ./...
          echo "Building Indexer..."
          go build -v ./...

      - name: Test & Build API
        run: |
          cd api
          go mod download
          echo "Running API Tests..."
          go test -v ./...
          echo "Building API..."
          go build -v ./...